In [63]:
#read in the eCommerce data set

import pandas as pd

data = pd.read_csv('e_commerce.csv', parse_dates=['CC Exp Date'])

In [ ]:
#read the data types of the columns and show how many null values there are.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [21]:
data.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,Provider
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95,morales-harrison.com
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04,olson-robinson.info
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82,gmail.com

In [12]:
# add a column 'Provider' that displays the email provider for each customer
# add a column with data_frame['new_column'] = data_frame['old_data'] + validation

data['Provider'] = data['Email'].apply(lambda x:x.split('@')[1])

data['Provider'].head()

0               yahoo.com
1                reed.com
2    morales-harrison.com
3     olson-robinson.info
4               gmail.com
Name: Provider, dtype: object

In [14]:
def get_email_provider(email):
    return email.split('@')[1]

In [16]:
data['Provider'] = data['Email'].apply(get_email_provider)

data['Provider'].head()

0               yahoo.com
1                reed.com
2    morales-harrison.com
3     olson-robinson.info
4               gmail.com
Name: Provider, dtype: object

In [20]:
# average purchase price

data['Purchase Price'].sum() / data['Purchase Price'].count()

50.347302

In [22]:
# max purchase price

data['Purchase Price'].max()

99.99

In [24]:
# how many people have 'en' as language of choice for their browser?

data[data['Language'] == 'en'].count()

Address             1098
Lot                 1098
AM or PM            1098
Browser Info        1098
Company             1098
Credit Card         1098
CC Exp Date         1098
CC Security Code    1098
CC Provider         1098
Email               1098
Job                 1098
IP Address          1098
Language            1098
Purchase Price      1098
Provider            1098
dtype: int64

In [25]:
# how many people made their purchase during the AM vs during PM?

data['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [30]:
# what are the 5 most common job titles?

data[['Job']].value_counts().head()

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Designer, jewellery                  27
Research officer, political party    27
dtype: int64

In [32]:
# how many people have American Express as their credit card provider and madea purchase above $95

data[(data['CC Provider'] == 'American Express') & (data['Purchase Price'] > 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
Provider            39
dtype: int64

In [62]:
#hard: how many people have a credit card that expires in 2025?

data['Date'] = pd.to_datetime(data['CC Exp Date'], format="%m/%y")

data[data['Date'].apply(lambda x: x.year == 2025)]

#data['Date'].apply(lambda x: x.dt.year == 25)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,Date
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82,2025-10-01
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15,2025-07-01
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25,2025-06-01
13,"118 Melton Via Suite 681\nAlexanderbury, FL 32104",36 bu,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Keller PLC,4603635169938574,01/25,557,VISA 16 digit,caitlin57@yahoo.com,"Accountant, chartered public finance",84.212.92.11,it,8.93,2025-01-01
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78,2025-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9955,"66539 Potts Forge\nCartershire, AK 58271-5180",37 KB,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows CE;...,Russell PLC,4716539058450,02/25,2805,JCB 16 digit,matthewcontreras@bradshaw-skinner.com,Podiatrist,88.110.181.120,zh,84.09,2025-02-01
9963,"3865 Davis Meadow Suite 915\nPort Stacieview, ...",11 fo,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,"Brown, Gentry and White",4295151255424068,07/25,764,JCB 15 digit,zjames@gmail.com,Surgeon,171.24.198.172,en,58.17,2025-07-01
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61,2025-10-01
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85,2025-01-01
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63,2025-07-01